#!/bin/bash
# Copyright 2020 Suyash Raghavendra and Aryash Raghavendra
# All Rights Reserved.

# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

if [ -z $1 ]; then
	sqlite3 .herobrine.db "SELECT username, gamename, SUBSTR(starttime, 1, 10) as date, substr(starttime, 12) as starttime, CASE endtime WHEN 'Online' THEN 'Online' ELSE substr(endtime, 12) END endtime, CASE endtime WHEN 'Online' THEN time(strftime('%s', 'now', 'localtime') - strftime('%s', starttime), 'unixepoch') ELSE time(time, 'unixepoch') END timespent FROM logblox WHERE starttime like '$(date +'%Y-%m-%d')%' ORDER BY username, starttime;" ".exit";
elif [ -z $2 ]; then
	sqlite3 .herobrine.db "SELECT username, gamename, SUBSTR(starttime, 1, 10) as date, substr(starttime, 12) as starttime, CASE endtime WHEN 'Online' THEN 'Online' ELSE substr(endtime, 12) END endtime, CASE endtime WHEN 'Online' THEN time(strftime('%s', 'now', 'localtime') - strftime('%s', starttime), 'unixepoch') ELSE time(time, 'unixepoch') END timespent FROM logblox WHERE username like '%$1%' and starttime like '$(date +'%Y-%m-%d')%' ORDER BY username, starttime;" ".exit";
else
	sqlite3 .herobrine.db "SELECT username, gamename, SUBSTR(starttime, 1, 10) as date, substr(starttime, 12) as starttime, CASE endtime WHEN 'Online' THEN 'Online' ELSE substr(endtime, 12) END endtime, CASE endtime WHEN 'Online' THEN time(strftime('%s', 'now', 'localtime') - strftime('%s', starttime), 'unixepoch') ELSE time(time, 'unixepoch') END timespent FROM logblox WHERE username like '%$1%' and starttime like '$2%' ORDER BY username, starttime;" ".exit";
fi
